spring:
  datasource:
    url: jdbc:mysql://localhost/elm?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop

    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true